/* Q7) Display the Id and Name of the Product ordered after “2021-10-05”. */

SELECT P.PRO_ID, P.PRO_NAME, O.ORD_DATE FROM PRODUCT p
INNER JOIN 
SUPPLIER_PRICING SP
ON P.PRO_ID = SP.PRO_ID
INNER JOIN `order` O
ON SP.PRICING_ID = O.PRICING_ID
WHERE O.ORD_DATE > "2021-10-05";